---
development:
  cloud_name: diisxovci
  api_key: '662189499346447'
  api_secret: OEenRpEm4B1RzQrqsUDyubgQepc
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: diisxovci
  api_key: '662189499346447'
  api_secret: OEenRpEm4B1RzQrqsUDyubgQepc
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: diisxovci
  api_key: '662189499346447'
  api_secret: OEenRpEm4B1RzQrqsUDyubgQepc
  enhance_image_tag: true
  static_image_support: false
