# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba3269ce66deb0f6771bc3db1920213060f36936ebd1d5cebf456da194c53573a2e2a3968de2f731f0a1afc7f763c65e5e3104b0c2bf97b20edabfada943777e

test:
  secret_key_base: 60701f9a8c5a31f77d0cb923c8b24d33e406d9bdc85901aa0c01167b806a78392414ff4c6c95115688203bf47e0f3b23bc39c5cb219cfe6ca5148247fb269747

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
